log-level = "debug"
node-ids = "ipn:1.0"

[grpc]
address = "[::1]:50061"
services = ["application", "cla", "service"]

[storage.metadata]
type = "memory"

[storage.bundle]
type = "memory"

# [built-in-services]
# echo = [7]

[[clas]]
name = "cspcl1"
type = "cspcl"
interface = { Can = "vcan0" }
local_addr = 1
local_port = 11
probe_interval_ms = 500
probe_timeout_ms = 250
keepalive_interval_ms = 500
peer_expiry_ms = 1500
ack_timeout_ms = 1000

[[clas.peers]]
node_ids = ["ipn:2.0"]
remote_addr = 2
remote_port = 11
